title: Signisto
description: Software Development &amp; Consultancy

gems:
- jekyll-assets

assets:
  digest: true
  features:
    automatic_img_size: false
  sources:
  - _assets/stylesheets
  - _assets/javascripts
  - _assets/images
  - _assets/fonts

exclude:
- Gemfile
- Gemfile.lock
- README.md
- bin
