title: Signisto
description: Software Development &amp; Consultancy

gems:
- jekyll-assets

assets:
  digest: true
  sources:
  - _assets/stylesheets
  - _assets/images

exclude:
- Gemfile
- Gemfile.lock
