# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: next build
      - run: next export -o dist
